config/routes.rb
MyStore::Application.routes.draw do
  
  resources :orders

  resources :line_items

  resources :carts

  resources :categories


  resources :items do
  	collection do
  		get 'inactive'
  	end
  end


  get "home/index"
  get "home/author"
  get "home/chantry"
  get "home/help"
  get "carts/show"
  root 'items#index'

  devise_for :users
  ActiveAdmin.routes(self)

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
    has_many :items, :through => :line_items
    
	def add_item(item_id)
           current_item = line_items.find_by(item_id: item_id)
        if current_item
           current_item.quantity += 1
    else
        current_item = line_items.build(item_id: item_id)
    end
        current_item
    end

    def sum_quantity
    	line_items.map(&:quantity).sum
    end

    def sum_weight
       items.map(&:weight).sum
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end

end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base
before_action :set_cart, only: [:show, :edit, :update, :destroy]
rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

    def show

    end


    def index

    end

    def set_cart
        @cart = Cart.find(session[:cart_id])
        rescue ActiveRecord::RecordNotFound
        @cart = Cart.create
        session[:cart_id] = @cart.id
    end

    def invalid_cart
        logger.error "Attempt to access invalid cart #{params[:id]}"
        redirect_to store_url, notice: 'Invalid cart'
    end

    def destroy
        @cart.destroy if @cart.id == session[:cart_id]
            session[:cart_id] = nil
            respond_to do |format|
            format.html { redirect_to home_index_url,
        notice: 'Your cart is currently empty' }
            format.json { head :no_content }
    end
end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<p id="notice"><%= notice %></p>

<table>
	
   <% @cart.line_items.each do |item| %>
       <tr>
           <li><%= item.quantity %> &times;</li>
           <li> <%= item.item.title %></li>
           <td class="item_price"><%= number_to_currency(item.total_price) %></td>
         </tr>
    <% end %>
    <tr class="total_line">
      <td colspan="2">Total</td>
          <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
    </tr>
</table>

<%= button_to "Checkout", new_order_path, method: :get %>
<%= button_to 'Empty cart', cart, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total_amount %><br>
    <%= f.number_field :total_amount %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<table>
	
   <% @cart.line_items.each do |item| %>
       <tr>
           <li><%= item.quantity %> &times;</li>
           <li> <%= item.item.title %></li>
           <td class="item_price"><%= number_to_currency(item.total_price) %></td>
         </tr>
    <% end %>
    <tr class="total_line">
      <td colspan="2">Total</td>
          <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
    </tr>
</table>

<p>
  <strong>Total amount:</strong>
  <%= @cart.sum_quantity %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @cart.sum_weight %>
</p>

<%= button_to 'Empty cart', @cart, method: :delete,
data: { confirm: 'Are you sure?' } %>


<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back to shop', home_index_path %> |
<%= link_to 'Buy', new_order_path %>