config/routes.rb
MyStore::Application.routes.draw do
  
  resources :orders

  resources :line_items

  resources :carts

  resources :categories


  resources :items do
  	collection do
  		get 'inactive'
  	end
  end


  get "home/index"
  get "home/author"
  get "home/chantry"
  get "home/help"
  get "carts/show"
  root 'items#index'

  devise_for :users
  ActiveAdmin.routes(self)

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyStore" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    
  </head>
  <body>
    <div id="fb-root"></div>
      <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
</script>
<nav role="navigation" class="navbar navbar">
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse"> 
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>  
          </a>
          <%= image_tag "banner.jpg" %>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home",home_index_path %></li>
              <li><%= link_to "About the authors",home_author_path %></li>
              <li><%= link_to "Association",home_chantry_path %></li>
              <li><%= link_to "Contact", home_help_path %></li>
            </ul>
            <ul class="nav pull-right">
                 <% if user_signed_in? %>
                 <li><%= link_to "Administrative panel", admin_root_path if current_user.admin %></li>
              <li><%= link_to "Edit", edit_user_registration_path  %></li>
              <li><%= link_to "Log out",  destroy_user_session_path, :method=>'delete'  %></li>
               <% else %>
              <li><%= link_to 'Log in', new_user_session_path %></li>
               <li><%= link_to 'Register', new_user_registration_path %></li>
               <% end %>
                <li><%= link_to "Cart", cart_path(@cart || Cart.create.id) %></li>
            </ul>
          </div><!--/.nav-collapse -->
      </div>
    </div>
</nav>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header"> <%= link_to "Browse by category", categories_path %></li>
              <div class="fb-like" data-href="http://localhost:3000/home/index" data-width="13" data-layout="standard" data-action="like" data-show-faces="true" data-share="true">
          </div>
        </div><!--/.well -->
      </div><!--/span-->
            </ul>

            <div class="span9">
                <ul class="nav pull-center">
                  <%= bootstrap_flash %>
                    <%= yield %>
                </ul>
              </div>
  
      </div><!--/row-->
      <footer>
        <p>&copy; by Stella 2014</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>